### ISSUE TITLE
Additional work todo after starting first test example

### ISSUE THREAD

**Issue by bieli** [behave-restful/behave-restful#62]
I'm impressed for this library and in this issu I give my feedback about strarting with this.
One thing expected in documentation but not exists it's: we need to add sth. like this in `environment.py`:
```python
import logging
import requests


def before_all(context):
    class Vars:
        @staticmethod
        def resolve(url: str):
            return url

    context.vars = Vars()
    context.session = requests
```
Only with below code example from README starting and scenario finised with green status.
Without below code I can see:
```bash
  Scenario: Add a new book to collection.                                               # features/AttributeAPI.feature:5
    Given a request url http://localhost:8080/v1/endpoint                                   # venv/lib/python3.7/site-packages/behave_restful/lang/_given_steps.py:7 0.000s
      Traceback (most recent call last):
        File "/home/test/bdd-testing/venv/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/test/bdd-testing/venv/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "/home/test/bdd-testing/venv/lib/python3.7/site-packages/behave_restful/lang/_given_steps.py", line 9, in step_impl
          _builder.set_url(context, url)
        File "/home/test/bdd-testing/venv/lib/python3.7/site-packages/behave_restful/_lang_imp/request_builder.py", line 8, in set_url
          resolved_url = context.vars.resolve(url)
        File "/home/test/bdd-testing/venv/lib/python3.7/site-packages/behave/runner.py", line 321, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'vars'
```
My requirements versions:
```bash
behave==1.2.6
behave-restful==0.3.1
```

**Comment by CurroRodriguez** [comment]
@bieli Thanks for your comment. 

Have you copied the required code provided for `environment.py`. The readme shows the code that you need so that variables are resolved.

I'm hoping to get to the documentation soon; although you can build the existing documentation yourself if you clone this repo. Make sure you create a virtual environment for the project, install the requirements, and run the make files depending on your system located in the docs/ folder.
